import React from 'react';

const DropDown = ({ filtered, clickHandler }) => {
    return (
        <>
            <button
                className="author-button"
                value={filtered[0]}
                onClick={clickHandler}
            >
                {filtered[0]}
            </button>
            <button
                className="author-button"
                value={filtered[0]}
                onClick={clickHandler}
            >
                {filtered[1]}
            </button>
            <button
                className="author-button"
                value={filtered[0]}
                onClick={clickHandler}
            >
                {filtered[2]}
            </button>
            <button
                className="author-button"
                value={filtered[0]}
                onClick={clickHandler}
            >
                {filtered[3]}
            </button>
            <button
                className="author-button"
                value={filtered[0]}
                onClick={clickHandler}
            >
                {filtered[4]}
            </button>
            <button
                className="author-button"
                value={filtered[0]}
                onClick={clickHandler}
            >
                {filtered[5]}
            </button>
            <button
                className="author-button"
                value={filtered[0]}
                onClick={clickHandler}
            >
                {filtered[6]}
            </button>
            <button
                className="author-button"
                value={filtered[0]}
                onClick={clickHandler}
            >
                {filtered[7]}
            </button>
            <button
                className="author-button"
                value={filtered[0]}
                onClick={clickHandler}
            >
                {filtered[8]}
            </button>
            <button
                className="author-button"
                value={filtered[0]}
                onClick={clickHandler}
            >
                {filtered[9]}
            </button>
        </>
    )
}

export default DropDown